# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Digital Acquisiton Accelerator Playbook
email: dap-18f@gsa.gov
description: > # this means to ignore newlines until "baseurl:"
  This playbook provides guidelines on how to approach digital acquistions within your agency. The playbook is broken down by first defining digital acquisitions, detailing out the phases of a digital acguisition, and then providing primers on a few key modern digital practices. You'll learn about the importance of building cross-functional teams, how to create a product strategy before solicitation, and this will provide an overview on agile, lean, human-centered design, open innovation, and modular contracting.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://pages.18f.gov/daap-playbook/" # the base hostname & protocol for your site
# twitter_username: jekyllrb
# github_username:  jekyll

# Build settings
markdown: kramdown
